---
title: "R Notebook"
output: html_notebook
---

# Classroom 7
This week covers chapter 5 in Gill which is derivatives and integrals. We will be practicing L'Hospital's rule, logarithmic differentiation, definite integrals, split integrals and more. I have provided many hints which can be found at the bottom of the notebook as I am unfortunately not present in class this week. I will as usual upload a solution to the git for the course by the end of Wednesday. 

## 5.1
*Hint 1


## 5.2
*Hint 2


## 5.3
*Hint 3


## 5.5
*Hint 5


## 5.7
*Hint 7


## 5.8


## 5.10
*Hint 10


## 5.11
This is a slightly harder exercise. Thus, I will provide more hints ;)

*Hint 11.1, 11.2, 11.3


Hint 1: Have a look at example 5.1 and 5.2 in Gill
Hint 2: Look at the properties of limits (specifically the properties of addition and subtraction, multiplication and scalar multiplication) page 181 in Gill
Hint 3: Notice that these are infinite limits (thus we can use L'Hospital's rule).
Hint 5: Use the power rule for derivatives $\frac{d}{d x} x^n=n x^{n-1}$
Hint 7: See page 197 in Gill use logarithmic differentiation
Hint 10: Use the fundamental theorem of calculus as seen on page 211 in Gill
Hint 11.1: First consider how the parabola of f(x) looks. Is it happy or sad?
Hint 11.2: What are the roots of the polynomial?
Hint 11.3: Compute definite split integrals
